# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com

language: node_js
before_script:
  - npm install -g gulp
script: gulp
